version: '3.8'

services:
  front:
    build: ../demo_ci_front
    volumes:
      - ../demo_ci_front/src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  api:
    build: .
    command: sh -c "npm start"
    environment:
      - PORT=4000
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      # - "host.docker.internal:host-gateway"
      - "host.docker.internal:172.17.0.1"
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d wilders -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wilders
    ports:
      - 5432:5432

    volumes:
      - wilders-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    

volumes:
  wilders-data: